### ISSUE TITLE
DOCS: Add `FAQ` component

### ISSUE THREAD

**Issue by wijohnst** [wijohnst/thriving-park-documentation#14]
This issue adds the `FAQ` component, which will be part of the landing page for the documentation. 

<img width="1030" alt="Screen Shot 2022-03-21 at 6 03 23 PM" src="https://user-images.githubusercontent.com/12022922/159371036-e45490fe-137c-43d1-a6d7-67957b1ef6e1.png">

The `<FAQ />` component, shown above, is a display component that will accept 2 props:

1. `questionText` 
2. `answerText` 

The specific styling for the HTML elements should be referenced from Figma. 

**Sub-Tasks**

- [ ] Add `FAQ` directory to `src/components` 
- [ ] Add `styles.modules.css` file
- [ ] Add `FAQ.jsx` file
